### ISSUE TITLE
Membuat halaman about, Edit footer, Mengedit Halaman utama (Carousel, Waktu durasi carousel)

### ISSUE THREAD

**Issue by Gilangdwi014** [Gilangdwi014/tubes-pw-laraboo#26]
Deskripsi About : Website Cooking Master merupakan website yang menyediakan berbagai macam resep masakan, 
mulai dari menu utama, minuman sampai ke hidangan penutup/dessert, 
Pengguna bisa melihat berbagai macam resep, cara pembuatan, hingga feedback pengguna lain, 
apabila pengguna ingin melihat resep yang ingin dia lakukan bisa menggunakan fitur bookmark

Durasi carousel (10 detik)

**Comment by MFathurrohmanHaris** [comment]
contoh kalimat di carousel nya tulis disini lang @Gilangdwi014

**Comment by MFathurrohmanHaris** [comment]
- [x] waktu carousel 10 detik
- [x] halaman about
- [x] edit footer
